// Generated by CoffeeScript 1.6.2
(function() {
  var countries, csv, fs, _;

  fs = require('fs');

  csv = require('csv');

  _ = require('underscore');

  countries = require(__dirname + '/countries');

  ({
    "type": "Feature",
    "id": "FRG",
    "properties": {},
    "c": "SA"
  });

  csv().from.path(__dirname + '/country_to_continent.csv').to.array(function(data) {
    var updatedCountries;

    data = _.object(data);
    updatedCountries = _.map(countries.features, function(country) {
      var iso;

      iso = country.properties.iso_a2;
      country.id = country.properties.iso_a2;
      country.c = data[iso];
      if (iso === '-99') {
        switch (country.properties.name) {
          case 'N. Cyprus':
            country.c = 'EU';
            break;
          case 'Kosovo':
            country.c = 'EU';
            break;
          case 'Somaliland':
            country.c = 'AF';
        }
      }
      delete country.properties;
      return country;
    });
    updatedCountries = _.filter(updatedCountries, function(country) {
      if (country.id === 'AQ') {
        console.log('found antarctica');
        return false;
      } else {
        return true;
      }
    });
    return fs.writeFile('updated_countries.js', JSON.stringify(updatedCountries), function(err) {
      if (err) {
        throw err;
      } else {
        return console.log('wee');
      }
    });
  });

}).call(this);
